### PR TITLE
Adding summary output

### PR DESCRIPTION
**Pull request by Ziqi-Li**
Adding summary output for GWR and MGWR. Related to #17 
Here is the [notebook](https://gist.github.com/Ziqi-Li/f27c669b888be28dc73f8313ddd90b08) showing the outputs.

### CODE REVIEW

**Comment by TaylorOshan** [comment]
Done in spglm/#7, should allow aicc to be calculated for GLMResults object.

**Comment by Ziqi-Li** [comment]
Thanks, just pushed a new commit reflecting that.

**Comment by TaylorOshan** [comment]
Looks good. A few potential tweaks:

1. Will the method work for Poisson/Binomial? They have slightly different model fit diagnostics
2. For MGWR, Should we add the corrected alpha value and corrected critical t-val for each variable next to ENP_J? This could be good to report.

**Comment by Ziqi-Li** [comment]
For 1, yes, it works for Poisson/Binomial, see [here](https://gist.github.com/Ziqi-Li/f27c669b888be28dc73f8313ddd90b08) at the bottom, I attached a summary output for the tokyo data.
For 2. Added the 95% covariate-specific t and alpha for mgwr in the new commit, also see [this](https://gist.github.com/Ziqi-Li/f27c669b888be28dc73f8313ddd90b08) in the mgwr output.

**Pull request merged**
